name: ai_bot
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4
  dash_chat_2: ^0.0.21
  delightful_toast: ^1.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter_gemini: ^2.0.4
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  markdown: ^7.2.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/ic_launcher_round.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # Uncomment and customize the fonts section if you need to add custom fonts
  # fonts:
  #   - family: Cera Pro
  #     fonts:
  #       - asset: assets/font/Cera-Pro-Bold.otf
  #       - asset: assets/font/Cera-Pro-Medium.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - assets/images/another_image.png
